server:
  port: ${PORT:8888}
spring:
  cloud:
    config:
      server:
        native:
          searchLocations:
          - file:../tempvs-config-repo/{application}/
          - file:../tempvs-config-repo/
        git:
          uri: https://github.com/ahlinist/tempvs-config-repo
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}
          force-pull: true
          search-paths: /,/{application}/
  security:
    user:
      name: ${CONFIG_AUTH_NAME:root}
      password: ${CONFIG_AUTH_PASSWORD:s3cr3t_pass}
