server:
  port: ${PORT:8888}
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ahlinist/tempvs-config-repo
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}
          force-pull: true
          search-paths: /,/{application}/
  security:
    user:
      name: ${AUTH_NAME}
      password: ${AUTH_PASSWORD}
